{{ if .Values.policies.checkDeprecatedApis.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-deprecated-apis
spec:
  validationFailureAction: {{ .Values.policies.checkDeprecatedApis.validationFailureAction }}
  rules:
  - name: validate-v1-22-removals
    match:
      resources:
        kinds:
        - admissionregistration.k8s.io/*/ValidatingWebhookConfiguration
        - admissionregistration.k8s.io/*/MutatingWebhookConfiguration
        - apiextensions.k8s.io/*/CustomResourceDefinition
        - apiregistration.k8s.io/*/APIService
        - authentication.k8s.io/*/TokenReview
        - authorization.k8s.io/*/SubjectAccessReview
        - authorization.k8s.io/*/LocalSubjectAccessReview
        - authorization.k8s.io/*/SelfSubjectAccessReview
        - certificates.k8s.io/*/CertificateSigningRequest
        - coordination.k8s.io/*/Lease
        - extensions/*/Ingress
        - networking.k8s.io/*/Ingress
        - networking.k8s.io/*/IngressClass
        - rbac.authorization.k8s.io/*/ClusterRole
        - rbac.authorization.k8s.io/*/ClusterRoleBinding
        - rbac.authorization.k8s.io/*/Role
        - rbac.authorization.k8s.io/*/RoleBinding
        - scheduling.k8s.io/*/PriorityClass
        - storage.k8s.io/*/CSIDriver
        - storage.k8s.io/*/CSINode
        - storage.k8s.io/*/StorageClass
        - storage.k8s.io/*/VolumeAttachment        
    {{- if or .Values.policies.checkDeprecatedApis.excludeSystemNamespaces  .Values.policies.checkDeprecatedApis.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.checkDeprecatedApis.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        {{- range .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        {{ `"{{ request.object.apiVersion }}/{{ request.object.kind }}"` }} is deprecated and will be removed in v1.22. 
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/        
      deny: {}
  - name: validate-v1-25-removals
    match:
      resources:
        kinds:
        - batch/*/CronJob
        - discovery.k8s.io/*/EndpointSlice
        - events.k8s.io/*/Event
        - policy/*/PodDisruptionBudget
        - policy/*/PodSecurityPolicy
        - node.k8s.io/*/RuntimeClass        
    {{- if or .Values.policies.checkDeprecatedApis.excludeSystemNamespaces  .Values.policies.checkDeprecatedApis.excludedNamespaces }}    
    exclude:
      resources:
        namespaces:
        {{- if .Values.policies.checkDeprecatedApis.excludeSystemNamespaces }}
        {{- range .Values.systemNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        {{- range .Values.policies.checkDeprecatedApis.excludedNamespaces }}
        - {{ . }}
        {{- end }}
        {{- end }}
    {{- end }}        
    validate:
      message: >-
        {{ `"{{ request.object.apiVersion }}/{{ request.object.kind }}"` }} is deprecated and will be removed in v1.25. 
        See: https://kubernetes.io/docs/reference/using-api/deprecation-guide/        
      deny: {}
{{ end }}      
